paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
      responses:
        "201":
          description: Producto creado correctamente
        "400":
          description: Datos de entrada inv치lidos
        "500":
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Producto obtenido correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    put:
      summary: Actualiza un producto existente
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
      responses:
        "200":
          description: Producto actualizado correctamente
        "400":
          description: Datos de entrada inv치lidos
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina un producto existente
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "204":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor

  /admin/products:
    get:
      summary: Obtiene todos los productos para el administrador
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
        "500":
          description: Error interno del servidor
  /:
    get:
      summary: Renderiza la p치gina de productos
      tags:
        - Products
      responses:
        "200":
          description: P치gina de productos renderizada correctamente
        "500":
          description: Error interno del servidor

